services:
 db:
   image: postgres:16-alpine
   environment:
     container_name: django-database
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

 django-web:
   build: .
   container_name: django-docker
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     DJANGO_SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     DATABASE_ENGINE: ${DB_ENGINE}
     DATABASE_NAME: ${DB_NAME}
     DATABASE_USERNAME: ${DB_USER}
     DATABASE_PASSWORD: ${DB_PASSWORD}
     DATABASE_HOST: ${DB_HOST}
     DATABASE_PORT: ${DB_PORT}
   env_file:
     - .env
volumes:
   postgres_data: